# Generated by Django 5.0.6 on 2025-05-24 14:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, default='', max_length=20, null=True, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(default='Alimento sin nombre', max_length=100, verbose_name='Nombre del Alimento')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('etapa', models.CharField(choices=[('INICIADOR', 'Iniciador (0-3 semanas)'), ('CRECIMIENTO', 'Crecimiento (3-6 semanas)'), ('DESARROLLO', 'Desarrollo (6-12 semanas)'), ('PREPOSTURA', 'Pre-postura (12-18 semanas)'), ('POSTURA_FASE1', 'Postura Fase 1 (18-40 semanas)'), ('POSTURA_FASE2', 'Postura Fase 2 (40+ semanas)'), ('ENGORDE_INICIAL', 'Engorde Inicial (0-10 días)'), ('ENGORDE_CRECIMIENTO', 'Engorde Crecimiento (11-22 días)'), ('ENGORDE_TERMINACION', 'Engorde Terminación (22+ días)')], default='INICIADOR', max_length=20, verbose_name='Etapa')),
                ('proteina_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Proteína (%)')),
                ('energia_metabolizable_kcal_kg', models.PositiveIntegerField(default=3000, verbose_name='Energía Metabolizable (Kcal/kg)')),
                ('stock_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock (kg)')),
                ('precio_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio por kg')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('lote_fabricante', models.CharField(blank=True, default='', max_length=50, verbose_name='Lote del Fabricante')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Alimento',
                'verbose_name_plural': 'Alimentos',
                'ordering': ['nombre', 'etapa'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad (kg)')),
                ('fecha_consumo', models.DateField(verbose_name='Fecha de Consumo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Consumo de Alimento',
                'verbose_name_plural': 'Consumos de Alimento',
                'ordering': ['-fecha_consumo', '-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='GuiaDesempenoRaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_edad', models.PositiveIntegerField(verbose_name='Día de Edad')),
                ('peso_corporal_ideal_gr', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Peso Corporal Ideal (gr)')),
                ('consumo_alimento_diario_ideal_gr_ave', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Consumo Diario Ideal (gr/ave)')),
                ('consumo_alimento_acumulado_ideal_gr_ave', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Consumo Alimento Acumulado Ideal (g/ave)')),
                ('conversion_alimenticia_ideal', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Conversión Alimenticia Ideal')),
                ('mortalidad_acumulada_ideal_porc', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Mortalidad Acumulada Ideal (%)')),
                ('ganancia_peso_diaria_ideal_gr', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Ganancia Peso Diaria Ideal (g)')),
                ('consumo_agua_diario_ideal_ml_ave', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Consumo Agua Diario Ideal (ml/ave)')),
                ('viabilidad_ideal_porc', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Viabilidad Ideal (%)')),
                ('epef_ideal', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='EPEF Ideal (Índice Europeo de Eficiencia Productiva)')),
                ('ie_ideal', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='IE Ideal (Índice de Eficiencia Energética)')),
            ],
            options={
                'verbose_name': 'Guía de Desempeño por Raza y Día',
                'verbose_name_plural': 'Guías de Desempeño por Raza y Día',
                'ordering': ['raza', 'dia_edad'],
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Insumo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo_insumo', models.CharField(choices=[('MEDICAMENTO', 'Medicamento'), ('EQUIPO', 'Equipo'), ('LIMPIEZA', 'Producto de Limpieza/Desinfección'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de Insumo')),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad en Stock')),
                ('unidad_medida', models.CharField(max_length=20, verbose_name='Unidad de Medida')),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock Mínimo')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('fecha_ingreso', models.DateField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('lote', models.CharField(blank=True, max_length=50, verbose_name='Lote')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rif', models.CharField(max_length=20, unique=True, verbose_name='RIF/CI')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre o Razón Social')),
                ('contacto_principal', models.CharField(blank=True, max_length=100, verbose_name='Persona de Contacto')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='Correo Electrónico')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Raza')),
                ('tipo_raza', models.CharField(choices=[('PONEDORA', 'Ponedora'), ('ENGORDE', 'Engorde'), ('DOBLE_PROPOSITO', 'Doble Propósito')], max_length=20, verbose_name='Tipo de Raza')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Raza',
                'verbose_name_plural': 'Razas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=100, verbose_name='Nombre Comercial')),
                ('principio_activo', models.CharField(max_length=150, verbose_name='Principio Activo / Enfermedad que previene')),
                ('lote_fabricante', models.CharField(blank=True, max_length=50, verbose_name='Lote del Fabricante')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('stock_ml', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock (ml)')),
                ('precio_ml', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por ml')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_ingreso', models.DateField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Vacuna',
                'verbose_name_plural': 'Vacunas',
                'ordering': ['nombre_comercial'],
            },
        ),
        migrations.CreateModel(
            name='AplicacionVacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aplicacion', models.DateField(verbose_name='Fecha de Aplicación')),
                ('dosis_ml', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Dosis Aplicada (ml)')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('lote_vacuna', models.CharField(blank=True, max_length=50, verbose_name='Lote de la Vacuna')),
                ('proxima_aplicacion', models.DateField(blank=True, null=True, verbose_name='Próxima Aplicación')),
                ('edad_aplicacion_semanas', models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad en Aplicación (semanas)')),
                ('via_aplicacion', models.CharField(blank=True, max_length=50, verbose_name='Vía de Aplicación')),
                ('aplicada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Aplicada por')),
            ],
            options={
                'verbose_name': 'Aplicación de Vacuna',
                'verbose_name_plural': 'Aplicaciones de Vacuna',
                'ordering': ['-fecha_aplicacion', '-fecha_registro'],
            },
        ),
    ]
