# Generated by Django 5.0.6 on 2025-05-24 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('produccion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacionvacuna',
            name='lote_aves',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones_vacuna', to='produccion.lote', verbose_name='Lote de Aves'),
        ),
        migrations.AddField(
            model_name='consumoalimento',
            name='alimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos', to='inventario.alimento', verbose_name='Alimento'),
        ),
        migrations.AddField(
            model_name='consumoalimento',
            name='lote_aves',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos_alimento', to='produccion.lote', verbose_name='Lote de Aves'),
        ),
        migrations.AddField(
            model_name='consumoalimento',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insumos_suministrados', to='inventario.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='alimento',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alimentos', to='inventario.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='guiadesempenoraza',
            name='raza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guias_desempeno', to='inventario.raza', verbose_name='Raza'),
        ),
        migrations.AddField(
            model_name='vacuna',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacunas_suministradas', to='inventario.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='aplicacionvacuna',
            name='vacuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones', to='inventario.vacuna', verbose_name='Vacuna'),
        ),
        migrations.AlterUniqueTogether(
            name='guiadesempenoraza',
            unique_together={('raza', 'dia_edad')},
        ),
    ]
