# Generated by Django 5.0.6 on 2025-05-24 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produccion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rif_cedula', models.CharField(max_length=20, unique=True, verbose_name='RIF/Cédula')),
                ('nombre_razon_social', models.CharField(max_length=150, verbose_name='Nombre o Razón Social')),
                ('contacto_principal', models.CharField(blank=True, max_length=100, verbose_name='Persona de Contacto')),
                ('telefono_principal', models.CharField(max_length=30, verbose_name='Teléfono Principal')),
                ('telefono_secundario', models.CharField(blank=True, max_length=30, verbose_name='Teléfono Secundario')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='Correo Electrónico')),
                ('direccion_fiscal', models.TextField(verbose_name='Dirección Fiscal')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre_razon_social'],
            },
        ),
        migrations.CreateModel(
            name='TipoHuevo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.CharField(choices=[('AA', 'AA (Extra Grande > 69g)'), ('A', 'A (Grande 60-68g)'), ('B', 'B (Mediano 53-59g)'), ('C', 'C (Pequeño 45-52g)'), ('D', 'D (Cartón < 45g)'), ('JUMBO', 'Jumbo (>70g)')], max_length=10, unique=True, verbose_name='Clasificación')),
                ('descripcion', models.CharField(blank=True, max_length=100, verbose_name='Descripción (ej: Peso rango)')),
            ],
            options={
                'verbose_name': 'Tipo de Huevo',
                'verbose_name_plural': 'Tipos de Huevo',
                'ordering': ['clasificacion'],
            },
        ),
        migrations.CreateModel(
            name='InventarioHuevos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso_inventario', models.DateField(auto_now_add=True, verbose_name='Fecha de Ingreso a Inventario')),
                ('cantidad_disponible', models.PositiveIntegerField(default=0, verbose_name='Cantidad Disponible (unidades)')),
                ('lote_produccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produccion.lote', verbose_name='Lote de Producción Origen')),
                ('tipo_huevo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.tipohuevo', verbose_name='Tipo de Huevo')),
            ],
            options={
                'verbose_name': 'Inventario de Huevos',
                'verbose_name_plural': 'Inventarios de Huevos',
                'ordering': ['tipo_huevo', '-fecha_ingreso_inventario'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Venta')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal')),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Impuesto (IVA)')),
                ('total_venta', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Venta')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='ventas.cliente', verbose_name='Cliente')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha_venta'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad Vendida (unidades)')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('subtotal_item', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal Item')),
                ('inventario_huevo_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.inventariohuevos', verbose_name='Del Inventario')),
                ('tipo_huevo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.tipohuevo', verbose_name='Tipo de Huevo Vendido')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
            },
        ),
    ]
