# Generated by Django 5.0.6 on 2025-05-24 14:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Reporte')),
                ('tipo_reporte', models.CharField(choices=[('PRODUCCION_DIARIA', 'Producción Diaria'), ('PRODUCCION_SEMANAL', 'Producción Semanal'), ('PRODUCCION_MENSUAL', 'Producción Mensual'), ('MORTALIDAD', 'Mortalidad'), ('INVENTARIO', 'Inventario'), ('VENTAS', 'Ventas'), ('COSTOS', 'Costos'), ('RENDIMIENTO', 'Rendimiento'), ('PERSONALIZADO', 'Personalizado')], max_length=50, verbose_name='Tipo de Reporte')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('formato', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV')], default='PDF', max_length=10, verbose_name='Formato')),
                ('fecha_generacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Generación')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='reportes/', verbose_name='Archivo Generado')),
                ('parametros', models.JSONField(blank=True, default=dict, verbose_name='Parámetros del Reporte')),
                ('usuario_generador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_generados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que generó')),
            ],
            options={
                'verbose_name': 'Reporte Generado',
                'verbose_name_plural': 'Reportes Generados',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Plantilla')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo_reporte', models.CharField(choices=[('PRODUCCION_DIARIA', 'Producción Diaria'), ('PRODUCCION_SEMANAL', 'Producción Semanal'), ('PRODUCCION_MENSUAL', 'Producción Mensual'), ('MORTALIDAD', 'Mortalidad'), ('INVENTARIO', 'Inventario'), ('VENTAS', 'Ventas'), ('COSTOS', 'Costos'), ('RENDIMIENTO', 'Rendimiento'), ('PERSONALIZADO', 'Personalizado')], max_length=50, verbose_name='Tipo de Reporte')),
                ('configuracion', models.JSONField(default=dict, verbose_name='Configuración de la Plantilla')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('es_predeterminada', models.BooleanField(default=False, verbose_name='Es Plantilla Predeterminada')),
                ('usuario_creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas_reporte', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Plantilla de Reporte',
                'verbose_name_plural': 'Plantillas de Reportes',
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'usuario_creador')},
            },
        ),
    ]
