# Generated by Django 5.0.6 on 2025-05-24 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Intención del Bot',
                'verbose_name_plural': 'Intenciones del Bot',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BotConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Hora de Inicio')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Finalización')),
                ('feedback_rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Calificación (1-5)')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='BotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('USER', 'Usuario'), ('BOT', 'Bot')], max_length=10, verbose_name='Remitente')),
                ('text', models.TextField(verbose_name='Texto')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Marca de Tiempo')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bot.botconversation', verbose_name='Conversación')),
                ('detected_intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='bot.botintent', verbose_name='Intención Detectada')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['conversation', 'timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BotResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Texto de Respuesta')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='bot.botintent', verbose_name='Intención')),
            ],
            options={
                'verbose_name': 'Respuesta del Bot',
                'verbose_name_plural': 'Respuestas del Bot',
                'ordering': ['intent', 'order'],
            },
        ),
        migrations.CreateModel(
            name='BotTrainingPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Texto')),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_phrases', to='bot.botintent', verbose_name='Intención')),
            ],
            options={
                'verbose_name': 'Frase de Entrenamiento',
                'verbose_name_plural': 'Frases de Entrenamiento',
            },
        ),
    ]
