# Generated by Django 5.0.6 on 2025-05-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortalidaddiaria',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='mortalidaddiaria',
            name='causa',
            field=models.CharField(blank=True, max_length=200, verbose_name='Causa de la Mortalidad'),
        ),
    ]
