# Generated by Django 5.2.1 on 2025-05-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_mortalidaddiaria_observaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galpon',
            name='tipo_galpon',
            field=models.CharField(choices=[('CRIA', 'Cría (Engorde)'), ('RECRIA', 'Recría (Engorde)'), ('POSTURA', 'Postura (Huevos)'), ('REPRODUCTOR', 'Reproductor'), ('CUARENTENA', 'Cuarentena')], default='POSTURA', max_length=20, verbose_name='Tipo de Galpón'),
        ),
    ]
