# Generated by Django 5.2.1 on 2025-05-27 17:34

from django.db import migrations, models
from django.conf import settings
import django.utils.timezone


def set_audit_fields(apps, schema_editor):
    Galpon = apps.get_model('produccion', 'Galpon')
    User = apps.get_model(settings.AUTH_USER_MODEL)
    
    # Get the first superuser or None
    try:
        admin_user = User.objects.filter(is_superuser=True).first()
    except:
        admin_user = None
    
    # Update all existing galpones
    Galpon.objects.all().update(
        fecha_creacion=django.utils.timezone.now(),
        creado_por=admin_user,
        actualizado_por=admin_user
    )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produccion', '0003_alter_galpon_tipo_galpon'),
    ]

    operations = [
        migrations.AddField(
            model_name='galpon',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='galpones_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado Por'),
        ),
        migrations.AddField(
            model_name='galpon',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='galpones_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por'),
        ),
        migrations.AddField(
            model_name='galpon',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AddField(
            model_name='galpon',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.RunPython(set_audit_fields, migrations.RunPython.noop),
    ]
