# Generated by Django 5.0.6 on 2025-05-24 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_backups', models.PositiveIntegerField(default=10, verbose_name='Máximo de Respaldos')),
                ('auto_backup_enabled', models.BooleanField(default=False, verbose_name='Respaldo Automático Habilitado')),
                ('auto_backup_frequency', models.PositiveIntegerField(default=24, verbose_name='Frecuencia de Respaldo (horas)')),
                ('include_database', models.BooleanField(default=True, verbose_name='Incluir Base de Datos')),
                ('include_media', models.BooleanField(default=True, verbose_name='Incluir Archivos de Medios')),
                ('compress_backup', models.BooleanField(default=True, verbose_name='Comprimir Respaldo')),
                ('encrypt_backup', models.BooleanField(default=False, verbose_name='Cifrar Respaldo')),
                ('notification_email', models.EmailField(blank=True, max_length=254, verbose_name='Email para Notificaciones')),
                ('last_auto_backup', models.DateTimeField(blank=True, null=True, verbose_name='Último Respaldo Automático')),
                ('backup_directory', models.CharField(default='backups', max_length=500, verbose_name='Directorio de Respaldos')),
            ],
            options={
                'verbose_name': 'Configuración de Respaldo',
                'verbose_name_plural': 'Configuraciones de Respaldo',
            },
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('file_path', models.CharField(max_length=500, verbose_name='Ruta del Archivo')),
                ('backup_type', models.CharField(choices=[('FULL', 'Respaldo Completo'), ('DB', 'Base de Datos'), ('MEDIA', 'Archivos de Medios')], default='FULL', max_length=10, verbose_name='Tipo de Respaldo')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En Progreso'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], default='PENDING', max_length=15, verbose_name='Estado')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='Tamaño (bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('is_auto', models.BooleanField(default=False, verbose_name='Automático')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Respaldo',
                'verbose_name_plural': 'Respaldos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'En Progreso'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], default='IN_PROGRESS', max_length=15, verbose_name='Estado')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inicio')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('log_output', models.TextField(blank=True, verbose_name='Salida de Log')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restore_logs', to='respaldos.backup', verbose_name='Respaldo')),
                ('restored_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restores', to=settings.AUTH_USER_MODEL, verbose_name='Restaurado por')),
            ],
            options={
                'verbose_name': 'Registro de Restauración',
                'verbose_name_plural': 'Registros de Restauración',
                'ordering': ['-started_at'],
            },
        ),
    ]
