# Generated by Django 5.0.6 on 2025-05-25 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avicola', '0002_alter_userprofile_groups_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Galpon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número de Galpón')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Galpón')),
                ('capacidad', models.PositiveIntegerField(verbose_name='Capacidad (aves)')),
                ('tipo', models.CharField(choices=[('crianza', 'Crianza'), ('postura', 'Postura'), ('engorde', 'Engorde'), ('recria', 'Recría')], max_length=20, verbose_name='Tipo de Galpón')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('mantenimiento', 'En Mantenimiento'), ('limpieza', 'En Limpieza')], default='activo', max_length=20, verbose_name='Estado')),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galpones', to='avicola.empresa', verbose_name='Empresa')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='galpones_a_cargo', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Galpón',
                'verbose_name_plural': 'Galpones',
                'ordering': ['numero'],
            },
        ),
    ]
